"""skema awal

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 06:49:37.744551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('syarat', sa.Text(), nullable=True),
    sa.Column('sla_info', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.String(length=200), nullable=True),
    sa.Column('template_name', sa.String(length=150), nullable=True),
    sa.Column('template_url', sa.String(length=255), nullable=True),
    sa.Column('require_kak', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_code', sa.String(length=12), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('nama_pemohon', sa.String(length=150), nullable=False),
    sa.Column('nip_nik', sa.String(length=30), nullable=False),
    sa.Column('opd', sa.String(length=150), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('antrean', 'verifikasi', 'disetujui', 'ditolak', name='status_pengajuan'), nullable=False),
    sa.Column('form_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('catatan', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_requests_nip_nik'), ['nip_nik'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_requests_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_requests_ticket_code'), ['ticket_code'], unique=True)

    op.create_table('request_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('status_from', sa.String(length=20), nullable=True),
    sa.Column('status_to', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_logs_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_logs_request_id'))

    op.drop_table('request_logs')
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_requests_ticket_code'))
        batch_op.drop_index(batch_op.f('ix_service_requests_status'))
        batch_op.drop_index(batch_op.f('ix_service_requests_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_requests_nip_nik'))

    op.drop_table('service_requests')
    op.drop_table('services')
    op.drop_table('categories')
    op.drop_table('admins')
    sa.Enum(name='status_pengajuan').drop(op.get_bind(), checkfirst=True)  # hapus tipe enum (PostgreSQL)
    # ### end Alembic commands ###
